### PR TITLE
Feature/load entry annotations

### PR DESCRIPTION
**Pull request by poltak**
This adds support for loading annots, with replies and reply functionality, to the shared list entries - when pressing the comments button

Notion doc: https://www.notion.so/worldbrain/Comment-icon-in-activities-should-unfold-the-comments-for-that-page-not-go-to-the-collection-6634c6412f4443648d291fc92edb943c

### CODE REVIEW

**Comment by ShishKabab** [comment]
Looks very good, nice work! You can merge this if you want. We coordinate on the scenarios to see how we're going to tackle that.

**Comment by poltak** [comment]
This wasn't yet finished - sorry for the lack of clarity. I was continuing communicating the issues on the notion doc, and neglected to put them here.

I figured out what was missing, stopping the replies from loading, which involved also mutating the conversations state. Now things are working!

I then encountered an issue where all of the new list entries were no longer showing up in the home-feed. After debugging a bit, I realized this was a result of your lists unfollow work in memex-common, which I updated to when bringing in other memex-common changes. As a result of that, in the test activities setup logic, I also needed to add a `services.activityStreams.followEntity` call for the list itself to allow those entries to show up in the feed - it didn't need this before, only the `storage.serverModules.activityFollows.storeFollow` call. I think I can understand why this is needed, though want to make sure that this was an intended change? 
Also, not exactly related to the recent changes, but why don't the example followed annotations need `activityFollows.storeFollow` calls?

**Comment by poltak** [comment]
I also just sorted out the merge conflicts. To do that I had to understand the changes you guys did in `fix/feed-split-screen`, particularly in the home-feed rendering logic. I think I got it ok and I haven't messed up anything, but great if you could double check that or refer me to a scenario where I can easily verify it

**Comment by ShishKabab** [comment]
Mmm, that's strange. What I remember is modifying the scenario loading the existing follow from a fixture, instead making it use `storeFollow`. `storeFollow` should still follow the activity by triggering the storage hook for following. There was a bug I ran into while implementing unfollowing that triggered the creation and deletion hook right after each other, so it would follow and unfollow straight away. But I did fix that, so it should work...

**Comment by ShishKabab** [comment]
I just verified the list entries show up in the feed without the `followEntity` call. If you think this branch is finished, you can merge it into `develop`  :)

**Pull request merged**
