### PR TITLE
Potential fix to input selection via stateful component

### PR DESCRIPTION
**Pull request by cdharris**
I had a quick look at the reported bug when using `TextInput` where writing text in the middle of a controlled component would reset the selection to the end.

I observed in the default case of a standard statefull component this issue was not present. The React issue mention keeping the update to within the components onChange.

So that's what I did here - swapping on the functional component and props update for a stateful component. The bug went away after doing that. 
l
Seems to make some sense to me that React will re-render the input in the functional case and therefore loose the selection, I tried adding a ref to aide it's reconciliation but the same issue appeared.

So not sure how it's best to generalise this solution, and also can't explain precisely why this satefull component manages to keep the auxiliary input state where as the functional component doesn't, but it doesn't seem totally unexpected, react probably has some extra references to work with.

Perhaps it's possible to create a statefull, controlled, TextInput as the generic component to alleviate the need to do this for every usage.

Thoughts @ShishKabab ?

### CODE REVIEW

**Comment by ShishKabab** [comment]
Thanks for the investigation! Yes, if it works to just keep state on level above the `<input>`, we can just make `<TextInput>` stateful. One variable that's left to investigate is how this works if you really hook this up to the state. In the PR, if I'm correct, state changes from the UILogic only get incorporated on render. If we change it dynamically, either in the Meta UI, or maybe as part of some other interaction, it won't get updated. That may also be the source of the bug: input change bubbles up, logic registers change, state change gets passed down in prop. It may be possible to reimplement `componentShouldUpdate()` and check if the current value and the incoming prop are (not) equal.

**Comment by cdharris** [comment]
>if it works to just keep state on level above the <input>, we can just make <TextInput> stateful.

> If we change it dynamically, either in the Meta UI, or maybe as part of some other interaction, it won't get updated.

Yes. I reverted the changes to the parent component, keeping that as is and did some tinkering with a stateful `TextInput` to make that work.

Following React's recent guidelines, suggested using `getDerivedStateFromProps`. So that's what I did.
As per their note, it did unceremoniously involve:
> fix this is to compare the incoming value to the previous value by storing the previous props in state:
https://reactjs.org/blog/2018/05/23/react-v-16-4.html#bugfix-for-getderivedstatefromprops

In general this prop - state mirroring seems to be considered an anti-pattern for every-day usage by react, but consider our usage within another framework (UI Logic) I guess we can allow it.
> https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

Perhaps you want to build a scenario that exercises this component in a test?

I'm done tinkering for now. Hopefully this helps :)

**Comment by ShishKabab** [comment]
Yup, it looks like this might work! Kind of weird this is necessary at all, but hey, if it allows us to move forward in a relatively clean way, all's good. The text input is already used in various scenarios which are currently broken, so this should fix those.

**Comment by seanc-dev** [comment]
Hey @ShishKabab @cdharris is it possible to use this same solution for the TextArea component? Need it for the profile edit dialog (branch feature/edit-user-profile).

**Pull request merged**
